// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/logreg/logreg.proto

package logreg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_proto_logreg_logreg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logreg_logreg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_logreg_logreg_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Request) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JWTToken      string                 `protobuf:"bytes,1,opt,name=JWTToken,proto3" json:"JWTToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_logreg_logreg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logreg_logreg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_logreg_logreg_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetJWTToken() string {
	if x != nil {
		return x.JWTToken
	}
	return ""
}

var File_proto_logreg_logreg_proto protoreflect.FileDescriptor

const file_proto_logreg_logreg_proto_rawDesc = "" +
	"\n" +
	"\x19proto/logreg/logreg.proto\x12\x06logreg\"A\n" +
	"\aRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"&\n" +
	"\bResponse\x12\x1a\n" +
	"\bJWTToken\x18\x01 \x01(\tR\bJWTToken2j\n" +
	"\rLogRegService\x12*\n" +
	"\x05Login\x12\x0f.logreg.Request\x1a\x10.logreg.Response\x12-\n" +
	"\bRegister\x12\x0f.logreg.Request\x1a\x10.logreg.ResponseB4Z2github.com/braginantonev/gcalc-server/proto/logregb\x06proto3"

var (
	file_proto_logreg_logreg_proto_rawDescOnce sync.Once
	file_proto_logreg_logreg_proto_rawDescData []byte
)

func file_proto_logreg_logreg_proto_rawDescGZIP() []byte {
	file_proto_logreg_logreg_proto_rawDescOnce.Do(func() {
		file_proto_logreg_logreg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_logreg_logreg_proto_rawDesc), len(file_proto_logreg_logreg_proto_rawDesc)))
	})
	return file_proto_logreg_logreg_proto_rawDescData
}

var file_proto_logreg_logreg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_logreg_logreg_proto_goTypes = []any{
	(*Request)(nil),  // 0: logreg.Request
	(*Response)(nil), // 1: logreg.Response
}
var file_proto_logreg_logreg_proto_depIdxs = []int32{
	0, // 0: logreg.LogRegService.Login:input_type -> logreg.Request
	0, // 1: logreg.LogRegService.Register:input_type -> logreg.Request
	1, // 2: logreg.LogRegService.Login:output_type -> logreg.Response
	1, // 3: logreg.LogRegService.Register:output_type -> logreg.Response
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_logreg_logreg_proto_init() }
func file_proto_logreg_logreg_proto_init() {
	if File_proto_logreg_logreg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_logreg_logreg_proto_rawDesc), len(file_proto_logreg_logreg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_logreg_logreg_proto_goTypes,
		DependencyIndexes: file_proto_logreg_logreg_proto_depIdxs,
		MessageInfos:      file_proto_logreg_logreg_proto_msgTypes,
	}.Build()
	File_proto_logreg_logreg_proto = out.File
	file_proto_logreg_logreg_proto_goTypes = nil
	file_proto_logreg_logreg_proto_depIdxs = nil
}
