// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: proto/logreg/logreg.proto

package logreg

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogRegService_Login_FullMethodName    = "/logreg.LogRegService/Login"
	LogRegService_Register_FullMethodName = "/logreg.LogRegService/Register"
)

// LogRegServiceClient is the client API for LogRegService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogRegServiceClient interface {
	Login(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Register(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type logRegServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogRegServiceClient(cc grpc.ClientConnInterface) LogRegServiceClient {
	return &logRegServiceClient{cc}
}

func (c *logRegServiceClient) Login(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, LogRegService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logRegServiceClient) Register(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, LogRegService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogRegServiceServer is the server API for LogRegService service.
// All implementations must embed UnimplementedLogRegServiceServer
// for forward compatibility.
type LogRegServiceServer interface {
	Login(context.Context, *Request) (*Response, error)
	Register(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedLogRegServiceServer()
}

// UnimplementedLogRegServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogRegServiceServer struct{}

func (UnimplementedLogRegServiceServer) Login(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedLogRegServiceServer) Register(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedLogRegServiceServer) mustEmbedUnimplementedLogRegServiceServer() {}
func (UnimplementedLogRegServiceServer) testEmbeddedByValue()                       {}

// UnsafeLogRegServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogRegServiceServer will
// result in compilation errors.
type UnsafeLogRegServiceServer interface {
	mustEmbedUnimplementedLogRegServiceServer()
}

func RegisterLogRegServiceServer(s grpc.ServiceRegistrar, srv LogRegServiceServer) {
	// If the following call pancis, it indicates UnimplementedLogRegServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogRegService_ServiceDesc, srv)
}

func _LogRegService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogRegServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogRegService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogRegServiceServer).Login(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogRegService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogRegServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogRegService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogRegServiceServer).Register(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// LogRegService_ServiceDesc is the grpc.ServiceDesc for LogRegService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogRegService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logreg.LogRegService",
	HandlerType: (*LogRegServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _LogRegService_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _LogRegService_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/logreg/logreg.proto",
}
